
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsImmService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8082/SIVTimm/WsImm?wsdl")
public class WsImmService
    extends Service
{

    private final static URL WSIMMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.WsImmService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.WsImmService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8082/SIVTimm/WsImm?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8082/SIVTimm/WsImm?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSIMMSERVICE_WSDL_LOCATION = url;
    }

    public WsImmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsImmService() {
        super(WSIMMSERVICE_WSDL_LOCATION, new QName("http://ws/", "WsImmService"));
    }

    /**
     * 
     * @return
     *     returns WsImm
     */
    @WebEndpoint(name = "WsImmPort")
    public WsImm getWsImmPort() {
        return super.getPort(new QName("http://ws/", "WsImmPort"), WsImm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsImm
     */
    @WebEndpoint(name = "WsImmPort")
    public WsImm getWsImmPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "WsImmPort"), WsImm.class, features);
    }

}
