
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsImm", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsImm {


    /**
     * 
     * @param arg0
     * @return
     *     returns ws.DataResultadoTicket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaTicket", targetNamespace = "http://ws/", className = "ws.AltaTicket")
    @ResponseWrapper(localName = "altaTicketResponse", targetNamespace = "http://ws/", className = "ws.AltaTicketResponse")
    public DataResultadoTicket altaTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        DataTicket arg0);

}
